site_name: Polydocs Documentation
site_url: https://docs.polydocs.io
site_author: Daniel Jordan
site_description: On these pages you will learn a lot about our different software helping you with digitization, digitalization and the digital transformation in your company.
theme:
  name: material
  custom_dir: overrides
  #favicon: _images/polydocs_Logo.svg
  favicon: _images/polydocs_Icon.svg
  font:
    text: Open Sans
  language: en
  logo: _images/polydocs_Icon.svg
  palette:
      scheme: light
      primary: indigo
  features:
    - navigation.instant
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+tabs#navigation-tabs
    - navigation.tabs
    - navigation.tabs.sticky
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+tabs#anchor-tracking
    - navigation.tracking
# https://squidfunk.github.io/mkdocs-material/customization/?h=#additional-css
extra_css:
  - _extra/css/extra.css
# https://squidfunk.github.io/mkdocs-material/customization/?h=#additional-javascript
extra_javascript:
  - _extra/javascript/extra.js
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  generator: false
  copyright: Copyright &copy; 2022 Polydocs GmbH
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/645725/
  analytics:
    provider: google
    property: UA-208531131-1
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://docs.google.com/forms/d/e/1FAIpQLScEh_N3lX4JFfvE1fdtImtSv2eVjcEGjlPzsH5usNfN4uNOIg/viewform?usp=pp_url&entry.1764397339=[Feedback]+{title}+-+{url}" target=_blank>feedback form</a>.
markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/?h=attr#attribute-lists attr_list is required for several other features. Always enable.
  - attr_list
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/?h=admoni
  - admonition
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#superfences Superfences is required for several other features. Always enable.
  - pymdownx.superfences
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#superfences Used for tags, setting unique templates for certain pages, and other custom frontmatter.
  - meta
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
  - pymdownx.highlight:
      linenums: true
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#inlinehilite
  - pymdownx.inlinehilite
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#snippets
  - pymdownx.snippets
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#tabbed
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  # https://www.mkdocs.org/user-guide/writing-your-docs/#linking-to-pages
  - toc:
      permalink: "#"
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search
  - literate-nav
  - tags:
      tags_file: tags.md
nav:
  - Changelog: Release/Release_notes.md
  - DOC²:
    - Getting Started: doc2/index.md
    - OnBoarding: doc2/onboarding.md
    - Deployment: doc2/deployment.md
    - Dashboard:
      - Dashboard: doc2/dashboard.md
      - Manual Import: doc2/manual-import.md
    - Document Validation:
      - Document Validation: doc2/document-validation.md
      - Master Data Validation: doc2/master-data-validation.md
      - OCR View: doc2/ocr-view.md
      - AI Indicator: doc2/ai-indicators.md
      - Expressions: doc2/exception-filters.md
    - Table:
      - Table Extraction: doc2/table/table-train.md
      - Train:
        - Table Extraction: doc2/table/training-of-table-extraction.md
        - Define tables and columns: doc2/table/define-table-and-columns.md
        - Add new Column: doc2/table/add-new-table-column.md
        - Mapping of Columns: doc2/mapping-of-columns.md
        - Group function: doc2/table/group-function.md
        - Manual row selection: doc2/table/manual-row-selection.md
        - Advanced settings: doc2/table/advanced-settings.md
        - Save and delete rules: doc2/table/save-rules-and-delete-rules.md
    - Keyboard: doc2/keyboard.md
    - DOC² with Infor: doc2/infor.md
    - DOC² with Workflow²: doc2/workflow.md
    - Settings:
      - General Settings: doc2/general settings.md
      - Company: doc2/company-information.md
      - Modules: doc2/modules.md
      - API: doc2/settings-api.md
      - Users: doc2/settings-users.md
      - All Import Options:
        - Overview: doc2/import.md
        - Email: doc2/e-mail.md
        - Fileshare Import:
          - Fileshare: doc2/fileshare.md
          - Configuration: doc2/watchpuppy-configuration.md
          - Linux: doc2/watchdog-linux.md
          - Windows: doc2/watchdog-windows.md
        - Webhook: doc2/api.md
      - All Export Options:
        - Export: doc2/export.md
        - Export to Infor:
          - Export to Infor ION and IDM: doc2/export/export-to-infor.md
          - How to create a BOD mapping file: doc2/export/how-to-create-a-bod-mapping-file.md
          - How to create a IDM mapping file: doc2/export/how-to-create-a-idm-mapping-file.md
          - Export to Infor IDM: doc2/export/infor-idm.md
          - Infor ION File: doc2/export/create-a-infor-ion-file.md
          - Export to Infor ION and IDM: doc2/export/infor-ion.md
        - Webhook: doc2/export/webhook.md
        - Export to Flow²: doc2/export/export-to-flow2.md


      - Amount: doc2/settings-amount-settings.md
      - Doc Types: doc2/settings-document-types.md
      - SSO:
        - Infor SSO: doc2/configuring-sso-in-cloud.md
      - Master Data Validation: doc2/settings-master-data-validation.md
    - PO Matching:
      - Overview: doc2/pomatching/po-matching.md
      - Delivery Note: doc2/pomatching/po-matching-delivery-notes.md
      - Invoices: doc2/pomatching/po-matching-invoices.md
      - Order Confirmation: doc2/pomatching/po-matching-order-confirmation.md

    - ZUGFeRD: doc2/zugpferd-and-peppol.md
    - SSO Settings: doc2/settings-sso-settings.md
    - Extracted fields: doc2/extracted-fields.md


  - Workflow²:
    - Overview: workflow/index.md
    - Try it out: workflow/quickstart.md
      - WF² Examples:
      - Replace Keys: example/replace.md
      - Weather: example/weather.md
      - Approval with Doc²: example/approval.md
      - New Order Workflow: example/workflow_mautic1.md
      - New Customer Workflow: example/workflow_mautic2.md
      - Doc² to Google Drive:
        - Create blank workflow: example/export-to-gdrive/create-blank-workflow.md
        - Configure Doc2StatusTrigger Node: example/export-to-gdrive/configure-doc2-status-trigger.md
        - Configure Google Drive Node: example/export-to-gdrive/configure-gdrive-node.md
        - Activate Workflow: example/export-to-gdrive/activate-workflow.md
    - Editor UI: workflow/editor-ui.md
    - Understand workflows:
      - Overview: workflow/workflows/index.md
      - Workflows: workflow/workflows/workflows.md
      - Connections: workflow/workflows/connections.md
      - Nodes: workflow/workflows/nodes.md
      - Notes: workflow/workflows/workflow-notes.md
      - Items: workflow/workflows/items.md
    - Flow logic:
      - Overview: workflow/flow-logic/index.md
      - Merging: workflow/flow-logic/merging.md
      - Looping: workflow/flow-logic/looping.md
      - Error handling: workflow/flow-logic/error-handling.md
    - Mapping and transforming data:
      - Overview: workflow/data/index.md
      - Data structure: workflow/data/data-structure.md
      - Transforming data: workflow/data/transforming-data.md
      - Using code: workflow/data/code.md
    - Code examples:
      - Overview: workflow/code-examples/index.md
      - Expressions:
        - Overview: workflow/code-examples/expressions/index.md
        - Methods: workflow/code-examples/expressions/methods.md
        - Variables: workflow/code-examples/expressions/variables.md
        - Data and time with Luxon: workflow/code-examples/expressions/luxon.md
        - JSON with JMESPath: workflow/code-examples/expressions/jmespath.md
      - JavaScript for workflows:
        - Overview: workflow/code-examples/javascript-functions/index.md
        - Methods: workflow/code-examples/javascript-functions/methods.md
        - Variables: workflow/code-examples/javascript-functions/variables.md
        - Get number of items returned by last node: workflow/code-examples/javascript-functions/number-items-last-node.md
        - Check incoming data: workflow/code-examples/javascript-functions/check-incoming-data.md
    - Reference:
      - Overview: workflow/reference/index.md
      - Release notes: workflow/reference/release-notes.md
      - CLI commands: workflow/reference/cli-commands.md
      - Keyboard shortcuts: workflow/reference/keyboard-shortcuts.md
      - Glossary: workflow/reference/glossary.md
      - License: workflow/reference/license.md
      - Data collection: workflow/reference/data-collection.md
    - Integrations:
      - Overview: workflow/integrations/index.md
      - Core nodes: workflow/integrations/core-nodes/
      - Nodes: workflow/integrations/nodes/
      - Trigger nodes: workflow/integrations/trigger-nodes/
      - Credentials: workflow/integrations/credentials/
      - Creating nodes:
        - Overview: workflow/integrations/creating-nodes/index.md
        - Code-based node building:
          - Overview: workflow/integrations/creating-nodes/code/index.md
          - Standards: workflow/integrations/creating-nodes/code/standards.md
          - Create your first node: workflow/integrations/creating-nodes/code/create-first-node.md
          - Create an Wf Nodes module: workflow/integrations/creating-nodes/code/create-wf-nodes-module.md
          - Create a trigger node: workflow/integrations/creating-nodes/code/create-trigger-node.md
          - Use the node developer CLI: workflow/integrations/creating-nodes/code/node-developer-cli.md
          - Node UI elements: workflow/integrations/creating-nodes/code/ui-elements.md
          - HTTP request helpers: workflow/integrations/creating-nodes/code/http-helpers.md
          - Node linter: workflow/integrations/creating-nodes/code/node-linter.md
          - Node review checklist: workflow/integrations/creating-nodes/code/review-checklist.md
          - Troubleshooting: workflow/integrations/creating-nodes/code/troubleshooting-node-development.md
  - FLOW²:
    - Introduction: flow2/index.md
    - Getting Started: flow2/introduction.md
    - Onboarding Guide: flow2/flow2-onboarding-guide.md
    - Deployment: flow2/deployment.md
    - User Dashboard: flow2/home.md
    - System Setup: flow2/settings-system-setup.md
    - Metadata: flow2/metadata.md
    - Import from Doc²: flow2/import-from-doc2.md
  - KV²:
    - Getting Started: kv2/getting-started.md
    - Installation: kv2/installation.md
    - Tutorial: kv2/kv2-tutorial.md
    - How To:
      - Training KV² for Table Extraction: kv2/training-kv2-for-table-extraction.md
      - Different VAT amounts: kv2/how-to-deal-with-different-vat-amounts.md
      - All Extracted Fields: kv2/all-extracted-fields.md
      - Rules: kv2/how-to-delete-a-kv2-plugin-rule-from-the-database.md
    - Restart Ephesoft:
      - Cloud: kv2/restart-ephesoft-on-cloud.md
      - OnPremise: kv2/restart-ephesoft-on-premise.md
    - Limitations: kv2/limitations-for-fellow-kv2-plugin.md
    - Feedback Function: kv2/enable-feedback-function.md
  - TE²:
    - Getting Started: te2/fellow-te2-plugin.md
    - Installation: te2/install.md
    - Tutorial: te2/fellowte2-tutorial.md
    - Ephesoft External Application: te2/ephesoft-external-application.md
    - Infor LN BOD Mapping: te2/ln_bodmapping.md
    - Feedback Function: te2/enable-feedback-function.md
  - OCR²:
    - Overview: ocr/overview.md
    - Installation & Config: ocr/installation-config.md
    - Getting Started: ocr/get-started.md
    - OCR Server Process: ocr/ocrserverprocess.md
    - Detect inside pages: ocr/detect-inside-pages.md
    - Merge/Split PDF: ocr/merge-split-pdf.md
    - API: ocr/ocr-api.md
  - WF² Examples:
    - Replace Keys: example/replace.md
    - Weather: example/weather.md
    - Approval with Doc²: example/approval.md
    - New Order Workflow: example/workflow_mautic1.md
    - New Customer Workflow: example/workflow_mautic2.md
    - Doc² to Google Drive:
      - Create blank workflow: example/export-to-gdrive/create-blank-workflow.md
      - Configure Doc2StatusTrigger Node: example/export-to-gdrive/configure-doc2-status-trigger.md
      - Configure Google Drive Node: example/export-to-gdrive/configure-gdrive-node.md
      - Activate Workflow: example/export-to-gdrive/activate-workflow.md
  - Insight²:
    - Action: app2/tutorial/actions.md
    - Datasource: app2/tutorial/adding-a-datasource.md
    - Widget: app2/tutorial/adding-widget.md

  # - Courses:
  #   - Overview: courses/index.md
  #   - Level one:
  #     - Overview: courses/level-one/index.md
  #     - Navigating the editor UI: courses/level-one/chapter-1.md
  #     - Building a mini-workflow: courses/level-one/chapter-2.md
  #     - Automating a (real-world) use case: courses/level-one/chapter-3.md
  #     - Designing the workflow: courses/level-one/chapter-4.md
  #     - Building the workflow:
  #       - Getting data from the data warehouse: courses/level-one/chapter-5/chapter-5.1.md
  #       - Inserting data into airtable: courses/level-one/chapter-5/chapter-5.2.md
  #       - Filtering orders: courses/level-one/chapter-5/chapter-5.3.md
  #       - Setting values for processing orders: courses/level-one/chapter-5/chapter-5.4.md
  #       - Calculating booked orders: courses/level-one/chapter-5/chapter-5.5.md
  #       - Notifying the team: courses/level-one/chapter-5/chapter-5.6.md
  #       - Scheduling the workflow: courses/level-one/chapter-5/chapter-5.7.md
  #       - Activating and examining the workflow: courses/level-one/chapter-5/chapter-5.8.md
  #     - Exporting, importing, and sharing workflows: courses/level-one/chapter-6.md
  #     - Take the quiz and get your certificate: courses/level-one/chapter-7.md


