[build]
  command = "pip install _submodules/insiders && mkdocs build"
  publish = "site"
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
		Content-Security-Policy = "frame-ancestors 'none'"

[[plugins]]
package = "netlify-plugin-checklinks"

	[plugins.inputs]
	checkExternal = true
